### ISSUE TITLE
Writing external (other languages) clients

### ISSUE THREAD

**Issue by kamikazechaser** [kalbhor/Tasqueue#24]
This is a great tool as it is one of the few written in Go that supports task chains.

I wanted to write a TS/JS client library to enqueue jobs from a Node.js app. From what I can see only the job payload is serialized to JSON while the Job opts isn't. This makes it impossible to directly enqueue a job on the respective broker. One way around this is to create an HTTP endpoint and send the job opts as JSON from the JS client, unmarshal this and enqueue it with the inbuilt Go NewJob -> Enqueue. An additional layer but workable with my scale (<10,000 reqs/enqueues / hr), but maybe not for others.

So:

- Does Tasqueue intend to be "celery like" that will allow any client to enqueue directly on to the broker with a Tasqueue specific JSON spec? This would be a significant API change.
- If not, is the current API spec and Tasqueue in general stable and production ready?

**Comment by kalbhor** [comment]
Hey, 
Tasqueue was written because we wanted a simple Go lib for distributing common tasks like jobs, chains, etc. Currently there is no plan to convert it into a “celery like” language agnostic job server.

- Although, the idea of a simple optional web server to accept jobs is interesting. This is okay for non critical usage. If you are interested, can fork and add that.

- I’ve been running tasqueue on few non critical production services as of now (400k jobs enqueued immediately). It seems to run smooth. The API spec may change down the line with proper versioning.

**Comment by kamikazechaser** [comment]
> If you are interested, can fork and add that.

Yeah sure, once I start working on it, I'll add it as an example.

**Comment by kalbhor** [comment]
Closing this for now since there are no plans to add support for external clients as of now
